services:
    server:
      build:
        context: .
        dockerfile: ./server/.docker/dev/Dockerfile
      container_name: ai-chatbot-server
      hostname: server
      restart: unless-stopped
      volumes:
        # Mount the path from the host machine, not the container
        - ${PROJECT_PATH}/ai-chatbot/server:/app
      ports:
        - ${SERVER_PORT}:5000
      command: >
        node /app/server.js

    app:
      build:
        context: .
        dockerfile: ./client/.docker/dev/Dockerfile
      container_name: ai-chatbot-client
      hostname: client
      restart: unless-stopped
      volumes:
        # Mount the path from the host machine, not the container
        - ${PROJECT_PATH}/ai-chatbot/client:/app
      ports:
        - ${VITE_PORT}:5173
      command: >
        run dev --host


  # web:
  #   build:
  #     context: .
  #     dockerfile: ./.docker/dev/Dockerfile
  #   restart: unless-stopped
  #   volumes:
  #     - .:/app
  #   ports:
  #     - 3000:3000
  #   command: >
  #     bash -c "cp -rfu /cache/node_modules/. /app/node_modules/  
  #     && npm start"
  # # test:
  # #   build:
  # #     context: .
  # #     dockerfile: ./.docker/dev/Dockerfile
  # #   volumes:
  # #     - .:/app
  # #   command: ["npm", "test"]