services:
    server:
      build:
        context: .
        dockerfile: ./server/.docker/dev/Dockerfile
      container_name: ai-chatbot-server
      hostname: server
      restart: unless-stopped
      volumes:
        # Mount the path from the host machine, not the container
        - ${PROJECT_PATH}/server:/app
      ports:
        - ${SERVER_PORT}:5000
      command: >
        node /app/server.js

    app:
      build:
        context: .
        dockerfile: ./client/.docker/dev/Dockerfile
      container_name: ai-chatbot-client
      hostname: client
      restart: unless-stopped
      volumes:
        # Mount the path from the host machine, not the container
        - ${PROJECT_PATH}/client:/app
      ports:
        - ${VITE_PORT}:5173
      command: >
        run dev --host